name: flutter_events
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.3 # BLoC
  flutter_bloc: ^8.0.1 # BLoC
  provider: ^6.0.3 # provide dependencies between viewmodel and widgets
  flutter_svg: ^1.1.1+1 # svg images
  path: ^1.8.1 # work with local folders
  sqflite: ^2.0.3 #database SQLite
  path_provider: ^2.0.11
  flutter_secure_storage: ^5.0.2
  json_annotation: ^4.6.0
  flutter_picker: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.3.1
  build_runner: ^2.2.0

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/event.svg
    - assets/events.json
